# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  derived_data_path = "DerivedDataTest"

  desc "Build test app"
  lane :build_test_app do
    run_tests(
      project: "TurboCalculator.xcodeproj",
      scheme: "TurboCalculator",
      build_for_testing: true,
      skip_build: true,
      derived_data_path: derived_data_path
    )
  end

  desc "Run UI-tests"
  lane :test_app do
    run_tests(
      project: "TurboCalculator.xcodeproj",
      scheme: "TurboCalculator",
      skip_build: true,
      test_without_building: true,
      device: "iPhone 14",
      reinstall_app: true,
      output_directory: "Build",
      result_bundle: true,
      force_quit_simulator: true,
      reset_simulator: true,
      app_identifier: "by.TurboCalculator",
      derived_data_path: derived_data_path
    )
  end
end
